// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASt_TdN_HfW3l8mVgnwydip9ZYQ1Caiks',
    appId: '1:921598256200:web:1447201b41a07ce1ebe47d',
    messagingSenderId: '921598256200',
    projectId: 'billyinventory-5dda3',
    authDomain: 'billyinventory-5dda3.firebaseapp.com',
    storageBucket: 'billyinventory-5dda3.appspot.com',
    measurementId: 'G-VGP0WRBZDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0A9eUcVK_BtxjAng7ObGxUZx6tvqPjfw',
    appId: '1:921598256200:android:03a7c7103f6e2dc2ebe47d',
    messagingSenderId: '921598256200',
    projectId: 'billyinventory-5dda3',
    storageBucket: 'billyinventory-5dda3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZm9tRGDJcG9yeNyWfOd6Jj5Rw-GK3Gn4',
    appId: '1:921598256200:ios:d422d821eb40a235ebe47d',
    messagingSenderId: '921598256200',
    projectId: 'billyinventory-5dda3',
    storageBucket: 'billyinventory-5dda3.appspot.com',
    iosClientId: '921598256200-rg5pc4vfq97vc21e7isrbpbpk4fnktj7.apps.googleusercontent.com',
    iosBundleId: 'com.example.billyinventory',
  );
}
